import Image from "next/image"
import logo from "@/components/alacran-logo.png"
import { cn } from "@/lib/utils"

/**
 * The Alacrán scorpion mark, the single identity shared with the marketing
 * site, which serves the same artwork as `landing/logo.png`.
 *
 * Generated by `scripts/generate-logo.py` from the supplied artwork; see that
 * script before changing the colour, and regenerate BOTH copies together.
 *
 * `unoptimized` is deliberate: the packaged desktop build has no `sharp`, and
 * running a 33 KB bundled PNG through the Image Optimization API at runtime
 * would buy nothing. A static import still emits the file into
 * `.next/static/media`, which `scripts/package-macos.sh` already copies.
 *
 * Sizing: pass a width utility (`w-16`), not `size-*`. The mark is 600x626,
 * so forcing a square would squash it. Height stays `h-auto`.
 */
export function AlacranMark({
  className,
  glow = false,
  priority = false,
}: {
  className?: string
  glow?: boolean
  priority?: boolean
}) {
  return (
    <Image
      src={logo}
      alt=""
      aria-hidden="true"
      unoptimized
      priority={priority}
      className={cn(
        "h-auto w-6 shrink-0 select-none",
        glow && "drop-shadow-[0_0_10px_color-mix(in_srgb,var(--primary)_65%,transparent)]",
        className
      )}
    />
  )
}
